name: style

on: [push, pull_request] 


jobs:
  mypy:
    name: Style Check with Black & isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: "python -m pip install black==19.10b0 isort==5.4.1"
        name: Install deps
      - run: "black --check --target-version py38 runner.py src"
        name: Format checking with black
      - run: "isort --profile=black runner.py src"
        name: import sorting
